name: Ubuntu - RDP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub provides hosted Ubuntu runners

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up the environment
      run: |
        sudo apt update
        sudo apt install -y xfce4 xfce4-goodies
        sudo apt install -y xrdp xorg dbus-x11 x11-xserver-utils

    - name: Configure RDP server
      run: |
        # Remove existing .xsession if it's a directory
        rm -rf ~/.xsession

        # Create necessary files for session configuration
        echo "xfce4-session" > ~/.xsession
        echo "startxfce4" | sudo tee -a /etc/skel/.xsession

        # Allow RDP traffic on port 3389
        sudo ufw allow 3389/tcp

        # Enable and start XRDP
        sudo systemctl enable xrdp
        sudo systemctl start xrdp

    - name: Install ngrok
      run: |
        wget -qO- https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip > ngrok.zip
        unzip ngrok.zip
        sudo mv ngrok /usr/local/bin/

    - name: Start ngrok for RDP
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }} # Add your ngrok auth token as a secret in GitHub
      run: |
        # Start ngrok to expose port 3389 for RDP
        nohup ngrok tcp 3389 --authtoken $NGROK_AUTH_TOKEN &
        sleep 10  # Allow ngrok some time to start

        # Display the public ngrok URL
        curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url'

    - name: Print connection details
      run: |
        echo "RDP Server is ready!"
        echo "Use the following connection details:"
        echo "Hostname: $(hostname)"
        echo "Local IP Address: $(hostname -I | awk '{print $1}')"
        echo "Public ngrok URL:"
        curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url'
        echo "Username: runner"
        echo "Password: (Use the GitHub runner's default password or set one manually)"

    - name: Check XRDP logs for errors
      run: |
        sudo cat /var/log/xrdp.log
        sudo cat /var/log/xrdp-sesman.log
