name: Ubuntu - RDP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub provides hosted Ubuntu runners

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up the environment
      run: |
        sudo apt update
        sudo apt install -y xfce4 xfce4-goodies
        sudo apt install -y xrdp xorg dbus-x11 x11-xserver-utils
        
        # Install dependencies for RDP
        sudo apt install -y xrdp

    - name: Configure RDP server
      run: |
        # Ensure .xsession is not a directory (remove if it exists)
        rm -rf ~/.xsession
        
        # Create necessary files for session configuration
        echo "xfce4-session" > ~/.xsession
        
        # Configure XRDP to use XFCE as the default session
        echo "startxfce4" | sudo tee -a /etc/skel/.xsession
        sudo ufw allow 3389/tcp
        
        sudo systemctl enable xrdp
        sudo systemctl start xrdp

    - name: Start RDP server
      run: |
        # Start the XRDP service
        sudo systemctl start xrdp
        sudo systemctl enable xrdp
        echo "RDP server is running."

    - name: Print system information
      run: |
        echo "RDP server running on display :0"
        echo "Use RDP client to connect with your runner's IP and port 3389"

    - name: Check XRDP log for errors
      run: |
        # Display XRDP logs to check if there are any errors
        sudo cat /var/log/xrdp.log
        sudo cat /var/log/xrdp-sesman.log

    - name: Wait for the server to finish
      run: |
        # Print the username and RDP password
        echo "RDP server is running..."
        echo Hostname: $(hostname)       # Get Hostname Form Ubuntu
        echo IP Address: $(hostname -i)  # Get IP Address Form Ubuntu
        echo "Username: runner"          # This is the default GitHub runner username
        echo "Password: 123456"          # Replace with your actual password, ideally from a secret
        echo "Use an RDP client to connect with the GitHub runner's IP and port 3389"
        sleep 1d
