name: Ubuntu - VNC

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub provides hosted Ubuntu runners

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up the environment
      run: |
        sudo apt update
        sudo apt install -y xfce4 xfce4-goodies
        sudo apt install -y tigervnc-standalone-server tigervnc-viewer

    - name: Configure VNC server
      run: |
        # Create the .vnc directory
        mkdir -p ~/.vnc
        
        # Set up a VNC password for the user. We can supply it non-interactively.
        echo "123456" | vncpasswd -f > ~/.vnc/passwd
        chmod 600 ~/.vnc/passwd
        
        # Set up a basic startup file for the VNC server (using XFCE).
        echo "#!/bin/bash" > ~/.vnc/xstartup
        echo "xrdb $HOME/.Xresources" >> ~/.vnc/xstartup
        echo "startxfce4 &" >> ~/.vnc/xstartup
        chmod +x ~/.vnc/xstartup

    - name: Start VNC server
      run: |
        # Start the VNC server on display 1 (you can change this as needed).
        vncserver :1 -geometry 1280x1024 -depth 24

    - name: Print system information
      run: |
        echo "VNC server running on display :1"
        echo "Use VNC viewer to connect with your runner's IP and port 5901"
        cat ~/.vnc/passwd

    - name: Wait for the server to finish
      run: |
        # Here you can add any additional actions or testing for the VNC server.
        echo "VNC server is running..."
